server:
  port: 8004

spring:
  application:
    name: maintenance-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/smg?useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

knowledge:
  service:
    url: http://localhost:8002

mybatis:
  configuration:
    map-underscore-to-camel-case: true

log:
  service:
    url: http://localhost:8009