server:
  port: 8009

spring:
  application:
    name: log-service
  datasource:
    url: jdbc:mysql://localhost:3306/smg?useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true

fault:
  report:
    export:
      path: D:\test