server:
  port: 8001

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/smg?useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
log:
  service:
    url: http://localhost:8009
