server:
  port: 8006

spring:
  application:
    name: system-service
  datasource:
    url: jdbc:mysql://localhost:3306/smg?useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
mybatis:
  mapper-locations: classpath*:system/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

log:
  service:
    url: http://localhost:8009