server:
  port: 8002

spring:
  application:
    name: knowledge-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678

log:
  service:
    url: http://localhost:8009