server:
  port: 8003

spring:
  application:
    name: kbm-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
knowledge:
  service:
    url: http://localhost:8002

log:
  service:
    url: http://localhost:8009